In [315]:
import numpy as np
import math

In [267]:
k = 2 # Numero de series temporais
p = 2 # lag
T = 5 # Tamanho das séries temporais

In [268]:
y1 = np.random.rand(T) # Serie temporal 1
y2 = np.random.rand(T) # Serie temporal 2

In [269]:
U = [[]] # Residuos

In [270]:
A = [[]] # Coeficientes

In [271]:
cov = [] # Matriz de covariancia

In [272]:
Y = np.transpose([y1[p:T], y2[p:T]])

In [286]:
Y

array([[0.77699802, 0.04631608],
       [0.04086029, 0.13841883],
       [0.12950902, 0.16578888]])

In [274]:
Z1 = np.zeros((T-p, p))
Z2 = np.zeros((T-p, p))

In [275]:
for i in range (T - p):
    for j in range(p):
        Z1[i][j] = y1[p+i-j-1]
        
for i in range (T - p):
    for j in range(p):
        Z2[i][j] = y2[p+i-j-1]

In [276]:
Z = np.concatenate((Z1, Z2), axis = 1)

In [288]:
Z

array([[0.25997874, 0.39986586, 0.15225942, 0.27994488],
       [0.77699802, 0.25997874, 0.04631608, 0.15225942],
       [0.04086029, 0.77699802, 0.13841883, 0.04631608]])

In [299]:
Z = np.insert(Z, 0, 1, axis = 1)

In [300]:
Zt = np.transpose(Z)

In [301]:
Zt

array([[1.        , 1.        , 1.        ],
       [0.25997874, 0.77699802, 0.04086029],
       [0.39986586, 0.25997874, 0.77699802],
       [0.15225942, 0.04631608, 0.13841883],
       [0.27994488, 0.15225942, 0.04631608]])

In [302]:
'''
A = m x p 
B = p x n 
C = m x n
'''

'\nA = m x p \nB = p x n \nC = m x n\n'

In [303]:
Z_Zt = np.dot(Zt, Z)

In [305]:
Z_Zt_I = np.linalg.inv(Z_Zt) 

In [306]:
Z_Zt_I_Zt = np.dot(Z_Zt_I, Zt) 

In [307]:
B = np.dot(Z_Zt_I_Zt, Y)

In [311]:
C = np.ones((p, k * p))

In [312]:
U = Y - np.dot(Z, B)

In [323]:
U

array([[ 0.28236497,  0.08969913],
       [-0.24892487, -0.12604922],
       [ 0.2342082 ,  0.08442013]])

In [317]:
varU1 = np.var(U, axis = 0)[0]
varU2 = np.var(U, axis = 0)[1]

In [322]:
Fxy, Fyx

(1.7405278212854876, -1.7405278212854876)