In [1]:
import pandas as pd
import statsmodels.tsa.stattools as stats

In [2]:
import numpy as np
import glob

In [3]:
x = pd.read_csv('X.csv').transpose().reset_index()['index']
y = pd.read_csv('Y.csv').transpose().reset_index()['index']

In [8]:
x = pd.Series(x)
y = pd.Series(y)

In [14]:
timeSeries = pd.DataFrame({'X' : x, 'Y' : y})

In [15]:
timeSeries

X                   Y
0      -1.48690042211667  -0.147548121917199
1     0.0525620827656984  -0.253230637929505
2      0.811108417883074  -0.981081974439613
3      0.741286569546029  -0.460840758665027
4      -2.03677236243252   -2.05642321398265
..                   ...                 ...
995  -0.0217685787020777    1.14531652945255
996    0.169952542442485  -0.480520362717404
997     1.09225431729033  -0.941913950467763
998   -0.105784939021341    -1.9427272983179
999    0.259584109437843  -0.275680102700411

[1000 rows x 2 columns]

In [20]:
Z = timeSeries[['X', 'Y']].to_numpy(dtype = float)

In [22]:
stats.grangercausalitytests(Z, 10, addconst=True, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0009  , p=0.9755  , df_denom=996, df_num=1
ssr based chi2 test:   chi2=0.0009  , p=0.9754  , df=1
likelihood ratio test: chi2=0.0009  , p=0.9754  , df=1
parameter F test:         F=0.0009  , p=0.9755  , df_denom=996, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0038  , p=0.9962  , df_denom=993, df_num=2
ssr based chi2 test:   chi2=0.0077  , p=0.9962  , df=2
likelihood ratio test: chi2=0.0077  , p=0.9962  , df=2
parameter F test:         F=0.0038  , p=0.9962  , df_denom=993, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.7009  , p=0.5516  , df_denom=990, df_num=3
ssr based chi2 test:   chi2=2.1177  , p=0.5483  , df=3
likelihood ratio test: chi2=2.1155  , p=0.5488  , df=3
parameter F test:         F=0.7009  , p=0.5516  , df_denom=990, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.6451  , p=0.6304  

{1: ({'ssr_ftest': (0.0009446205918882496, 0.9754872905295797, 996.0, 1),
   'ssr_chi2test': (0.000947465834634901, 0.9754442464985589, 1),
   'lrtest': (0.0009474653852521442, 0.9754442523201139, 1),
   'params_ftest': (0.0009446205916419571, 0.9754872905324483, 996.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.0038350839283399093, 0.9961722753688533, 993.0, 2),
   'ssr_chi2test': (0.007708789044276392, 0.9961530241219069, 2),
   'lrtest': (0.007708759272645693, 0.996153038950457, 2),
   'params_ftest': (0.0038350839286187665, 0.9961722753685788, 993.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.70094376043553, 0.5515767174656698, 990.0, 3),
   'ssr_chi2test': (2.117699785315829, 0.5483402840712561, 3),
   'lrtest': (2.1154538916357524, 0.5487926682979782, 3),
   'params_ftest': (0.7009437604354813, 0.5515767174657149, 990.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
      

In [17]:
Z

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       ...,
       [ True,  True],
       [ True,  True],
       [ True,  True]])